<?php use Application\Model\Utility\Utilidades; ?>
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="btn-toolbar float-right mb-2" aria-label="Barra de herramientas" role="toolbar" >
                <div class="" aria-label="First group" role="group">
                    <?php if($this->usuario->get('rol') == '4dmin'){ ?>
                        <a title="Crear candidatura" href="<?php echo $this->basePath('/backend/empleo/candidatura') ?>" aria-label="Crear candidatura" class="btn btn-light" data-toggle="tooltip"><i class="fa fa-plus"></i></a>
                    <?php } ?>
                    <a title="Buscar" href="#myModal" aria-label="Buscar" class="btn btn-light" data-toggle="modal" ><i class="fa fa-search"></i></a>
                    <?php if($this->usuario->get('rol') == '4dmin'){ ?>
                        <a title="Exportar a Excel" href="<?php echo $this->basePath('/backend/empleo/xlscandidaturas/') ?>" aria-label="Exportar a Excel" class="btn btn-light" data-toggle="tooltip"><i class="fa fa-file-excel"></i></a>
                    <?php } ?>
                    <a title="Mostrar todo" href="<?php echo $this->basePath('/backend/empleo/candidaturas/' . $this->page . '/114') ?>" aria-label="Mostrar todo" class="btn btn-light" data-toggle="tooltip"><i class="fa fa-sync"></i></a>
                </div>
            </div>
            <h1><i class="fa fa-address-card"></i> Candidaturas (<?php echo $this->num; ?>)</h1>
        </div>
    </div>
    <?php Utilidades::muestraMensaje($this->ok,$this->ko); ?>
</div>
<?php if(count($this->candidaturas)){ ?> 
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="table-responsive mt-2 white" >
                    <table class="table table-sm table-striped" >			
                        <thead class="b-color_4 table-header ">
                            <tr>
                                <th class="table-col-1">ID</th>
                                <th class="table-col-2">Usuario</th>
                                <th class="table-col-2">Oferta</th>
                                <th class="table-col-2">Empresa</th>
                                <th class="table-col-2 text-center">Creación</th>
                                <th class="table-col-2">Estado</th>
                                <th class="table-col-1 text-center">Opc.</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach($this->candidaturas as $candidatura): ?>
                                <tr>
                                    <td>
                                        <a href="<?php echo $this->basePath('/backend/empleo/candidatura/' . $candidatura['id_can']) ?>">
                                            <span class="badge badge-<?php echo Utilidades::systemOptions('candidaturas', 'estado',2)[(int)$candidatura['candidaturasEstado']]; ?>"><?php echo str_pad($candidatura['id_can'],5,'0',STR_PAD_LEFT); ?></span>
                                        </a>
                                    </td>
                                    <td>
                                        <?php if($this->usuario->get('rol') == '4dmin'){ ?>
                                            <a href="<?php echo $this->basePath('/backend/usuarios/ficha/' . $candidatura['id_usu']) ?>" title="" class="">
                                                <?php echo $candidatura['usuariosNombre']." ".$candidatura['usuariosApellidos']; ?>
                                            </a>
                                        <?php }else{ ?>
                                            <?php echo $candidatura['usuariosNombre']." ".$candidatura['usuariosApellidos']; ?>
                                        <?php } ?>
                                        <?php 
                                        if(!empty($candidatura['telefono'])){
                                            echo '<br/><small>'.$candidatura['telefono'].'</small>'; 
                                        }
                                        if(!empty($candidatura['email'])){
                                            echo '<br/><small>'.$candidatura['email'].'</small>';
                                        }
                                        ?>
                                    </td>
                                    <td><a href="<?php echo $this->basePath('/backend/empleo/candidatura/' . $candidatura['id_can']) ?>" title="" class=""><?php echo $candidatura['titulo']; ?></a></td>
                                    <td>
                                        <?php if($this->usuario->get('rol') == '4dmin'){ ?>
                                            <a href="<?php echo $this->basePath('/backend/empresas/ficha/' . $candidatura['id_emp']) ?>" title="" class="">
                                                <?php echo $candidatura['empresasNombre']; ?>
                                            </a>
                                        <?php }else{ ?>
                                            <?php echo $candidatura['empresasNombre']; ?>
                                        <?php } ?>
                                    </td>
                                    <td class="text-center"><?php echo Utilidades::giraFecha($candidatura['candidaturasFecha']); ?></td>
                                    <td><a href="<?php echo $this->basePath('/backend/empleo/candidatura/' . $candidatura['id_can']) ?>" title="" class=""><?php echo Utilidades::systemOptions('candidaturas', 'estado',1)[(int)$candidatura['candidaturasEstado']]; ?></a></td>
                                    <td class="text-center">
                                        <a href="<?php echo $this->basePath('/backend/empleo/candidatura/' . $candidatura['id_can']) ?>" title="Editar" class="btn btn-light btn-sm"><i class="fa fa-edit"></i></a>
                                        <a href="<?php echo $this->basePath('/backend/empleo/borrarcandidatura/' . $candidatura['id_can']) ?>" title="Borrar" class="btn btn-light btn-sm red" onclick="return confirm('&iquest;Est&aacute; seguro que desea borrar la candidatura?')" ><i class="fa fa-trash"></i></a>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                    <?php Utilidades::muestraPaginacion($this->num, $this->page, $this->basePath('/backend/empleo/candidaturas/'),50) ?>
                </div>
            </div>
        </div>
    </div>
<?php } ?>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" ><i class="fa fa-search"></i> B&uacute;squeda de candidaturas</h5>
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <form action="<?php echo $this->basePath('/backend/empleo/candidaturas') ?>" method="post" >
                <div class="modal-body">
                    <div class="row ">
                        <?php if($this->usuario->get('rol') == '4dmin'){ ?>
                            <div class="form-group col-12" >
                                <label for="usua-nombre" class="control-label">Usuario</label>
                                <input type="hidden" id="usua-nombre" name="id_usu" class="form-control usua-nombre" value="<?php echo (int)$this->buscador['id_usu']; ?>" />
                            </div>
                             <div class="form-group col-12" >
                                <label for="ofer-nombre" class="control-label">Oferta</label>
                                <input type="hidden" id="ofer-nombre" name="id_ofe" class="form-control ofer-nombre" value="<?php echo (int)$this->buscador['id_ofe']; ?>" />
                            </div>
                             <div class="form-group col-12" >
                                <label for="empr-nombre" class="control-label">Empresa</label>
                                <input type="hidden" id="empr-nombre" name="id_emp" class="form-control empr-nombre" value="<?php echo $this->buscador['id_emp']; ?>" />
                            </div>
                        <?php } ?>
                        <div class="form-group col-12" >
                            <label for="ofer-estado" class="control-label">Estado</label>
                            <?php echo Utilidades::getSelect($this->buscador['candidaturasEstado'],'candidaturas','estado',0,0,1); ?>
                        </div>
                        <div class="form-group col-6" >
                            <label for="cand-fechaDesde" class="control-label">Fecha (desde)</label>
                            <input type="text" id="cand-fechaDesde" name="fechaDesde" class="form-control form-control-sm cand-fechaDesde datepicker" value="<?php echo $this->buscador['fechaDesde']; ?>" />
                        </div>
                        <div class="form-group col-6" >
                            <label for="cand-fechaHasta" class="control-label">Fecha (hasta)</label>
                            <input type="text" id="cand-fechaHasta" name="fechaHasta" class="form-control form-control-sm cand-fechaHasta datepicker" value="<?php echo $this->buscador['fechaHasta']; ?>" />
                        </div>
                    </div>
                </div>
                <div class="modal-footer ">
                    <a href="<?php echo $this->basePath('/backend/empleo/candidaturas/' . $this->page . '/114') ?>" type="button" class="btn btn-light" >Limpiar</a>
                    <button type="submit" name="boton" value="buscar" class="btn btn-blue ">Buscar</button>
                </div>
            </form>
        </div>
    </div>
</div>