<?php use Application\Model\Utility\Utilidades; ?>
<div class="container">
    <div class="row">
        <div class="col-12 mb-2">
            <div class="btn-toolbar float-right" aria-label="Barra de herramientas" role="toolbar" >
                <div class="" aria-label="First group" role="group">
                    <a title="Crear inscripcion" href="<?php echo $this->basePath('/backend/formacion/inscripcion') ?>" aria-label="Crear inscripcion" class="btn btn-light d-none" data-toggle="tooltip"><i class="fa fa-plus"></i></a>
                    <a title="Buscar" href="#myModal" aria-label="Buscar" class="btn btn-light" data-toggle="modal" ><i class="fa fa-search"></i></a>
                    <?php if($this->usuario->get('rol') == '4dmin'){ ?>
                        <a title="Exportar a Excel" href="<?php echo $this->basePath('/backend/formacion/xlsinscripciones/') ?>" aria-label="Exportar a Excel" class="btn btn-light" data-toggle="tooltip"><i class="fa fa-file-excel"></i></a>
                    <?php } ?>
                    <a title="Mostrar todo" href="<?php echo $this->basePath('/backend/formacion/inscripciones/' . $this->page . '/114') ?>" aria-label="Mostrar todo" class="btn btn-light" data-toggle="tooltip"><i class="fa fa-sync"></i></a>
                </div>
            </div>
            <h1><i class="fa fa-edit"></i> Inscripciones (<?php echo $this->num; ?>)</h1>
        </div>
    </div>
    <?php Utilidades::muestraMensaje($this->ok,$this->ko); ?>
</div>
<?php if((int)$this->num){ ?> 
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="table-responsive mt-2 white" >
                    <table class="table table-sm table-striped" >			
                        <thead class="b-color_4 table-header ">
                            <tr>
                                <th class="table-col-1 text-center">ID</th>
                                <th class="table-col-2">Nombre</th>
                                <th class="table-col-2">Curso</th>
                                <th class="table-col-2 text-center">Fecha</th>
                                <th class="table-col-1">Importe</th>
                                <th class="table-col-1">Estado</th>
                                <th class="table-col-1 text-center">Pago</th>
                                <th class="table-col-1 text-center">Nº Inscritos</th>
                                <th class="table-col-1 text-center">Opc.</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach($this->inscripciones as $inscripcion): ?>
                                <tr>
                                    <td class="text-center">
                                        <a href="<?php echo $this->basePath('/backend/formacion/inscripcion/' . $inscripcion['id_ins']) ?>" >
                                            <span class="badge badge-<?php echo Utilidades::systemOptions('inscripciones', 'estado',2)[(int)$inscripcion['estado']]; ?>"><?php echo str_pad($inscripcion['id_ins'], 5, '0', STR_PAD_LEFT); ?></span>
                                        </a>
                                    </td>
                                    <td>
                                        <a href="<?php echo $this->basePath('/backend/usuarios/ficha/' . $inscripcion['id_usu']) ?>" title="Editar" class="">
                                            <?php echo $inscripcion['usuariosNombre']." ".$inscripcion['usuariosApellidos']; ?>
                                        </a>
                                        <?php 
                                        if(!empty($inscripcion['telefono'])){
                                            echo '<br/><small>'.$inscripcion['telefono'].'</small>'; 
                                        }
                                        if(!empty($inscripcion['email'])){
                                            echo '<br/><small>'.$inscripcion['email'].'</small>';
                                        }
                                        ?>
                                    </td>
                                    <td class="v-middle">
                                        <a href="<?php echo $this->basePath('/backend/formacion/curso/' . $inscripcion['id_cur']) ?>" title="Editar" class="">
                                            <?php echo $inscripcion['cursosNombre']; ?>
                                        </a>
                                        <?php echo '<br/><small>'.Utilidades::systemOptions('cursos', 'tipo')[$inscripcion['tipo']].'</small>'; ?>
                                    </td>
                                    <td class="text-center"><?php echo Utilidades::giraFecha($inscripcion['fecha']); ?></td>
                                    <td class="text-right"><?php echo number_format($inscripcion['importe'],2,'.',',').'&euro;'; ?></td>
                                    <td>
                                        <a href="<?php echo $this->basePath('/backend/formacion/inscripcion/' . $inscripcion['id_ins']) ?>" >
                                            <?php echo Utilidades::systemOptions('inscripciones', 'estado',1)[$inscripcion['estado']]; ?>
                                        </a>
                                    </td>
                                    <td class="text-center"><?php echo Utilidades::systemOptions('inscripciones', 'pago',1)[$inscripcion['pago']]; ?></td>
                                    <td class="text-center"><?php echo $inscripcion['inscritos']; ?></td>
                                    <td class="text-center">
                                        <a href="<?php echo $this->basePath('/backend/formacion/inscripcion/' . $inscripcion['id_ins']) ?>" title="Editar" class="btn btn-light btn-sm" ><i class="fa fa-edit"></i></a>
                                        <a href="<?php echo $this->basePath('/backend/formacion/borrarinscripcion/' . $inscripcion['id_ins']) ?>" title="Borrar" class="btn btn-light btn-sm red" onclick="return confirm('&iquest;Est&aacute; seguro que desea borrar la inscripción?')" ><i class="fa fa-trash"></i></a>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                    <?php Utilidades::muestraPaginacion($this->num, $this->page, $this->basePath('/backend/formacion/inscripciones/'),50) ?>
                </div>
            </div>
        </div>
    </div>
<?php } ?>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" ><i class="fa fa-search"></i> B&uacute;squeda de inscripciones</h5>
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <form action="<?php echo $this->basePath('/backend/formacion/inscripciones') ?>" method="post" >
                <div class="modal-body">
                    <div class="row ">
                        <div class="form-group col-12" >
                            <label for="usua-nombre" class="control-label">Nombre</label>
                            <input type="hidden" id="usua-nombre" name="id_usu" class="form-control usua-nombre" value="<?php echo (int)$this->buscador['id_usu']; ?>" />
                        </div>
                        <div class="form-group col-12" >
                            <label for="curs-nombre" class="control-label">Curso</label>
                            <input type="hidden" id="curs-nombre" name="id_cur" class="form-control curs-nombre" value="<?php echo (int)$this->buscador['id_cur']; ?>" />
                        </div>
                        <div class="form-group col-12" >
                            <label for="incs-estado" class="control-label">Estado</label>
                            <?php echo Utilidades::getSelect($this->buscador['estado'],'inscripciones','estado',0,0,1); ?>
                        </div>
                        <div class="form-group col-6" >
                            <label for="incs-fechaDesde" class="control-label">Fecha (desde)</label>
                            <input type="text" id="incs-fechaDesde" name="fechaDesde" class="form-control form-control-sm incs-fechaDesde datepicker" value="<?php echo $this->buscador['fechaDesde']; ?>" />
                        </div>
                        <div class="form-group col-6" >
                            <label for="incs-fechaHasta" class="control-label">Fecha (hasta)</label>
                            <input type="text" id="incs-fechaHasta" name="fechaHasta" class="form-control form-control-sm incs-fechaHasta datepicker" value="<?php echo $this->buscador['fechaHasta']; ?>" />
                        </div>
                        <div class="form-group col-12 col-md-6" >
                            <label for="incs-tipo" class="control-label">Tipo</label>
                            <?php echo Utilidades::getSelect($this->buscador['tipo'],'cursos','tipo',0,0,1); ?>
                        </div>
                        <div class="form-group col-12 col-md-6" >
                            <label for="incs-pago" class="control-label">Pago</label>
                            <?php echo Utilidades::getSelect($this->buscador['pago'],'inscripciones','pago',0,0,1); ?>
                        </div>
                    </div>
                </div>
                <div class="modal-footer ">
                    <a href="<?php echo $this->basePath('/backend/formacion/inscripciones/' . $this->page . '/114') ?>" type="button" class="btn btn-light" >Limpiar</a>
                    <button type="submit" name="boton" value="buscar" class="btn btn-blue ">Buscar</button>
                </div>
            </form>
        </div>
    </div>
</div>