<?php echo $this->doctype(); ?>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->title.' | Colegio Oficial de Ingenieros Industriales de Andalucía Occidental')->setSeparator(' - ')->setAutoEscape(false); ?>
        <?php echo $this->headMeta()
                        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <?php echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath('assets/images/coiiaoc.jpg')])
            ->prependStylesheet($this->basePath('assets/css/site.css?v=1.1'))
            ->prependStylesheet($this->basePath('assets/css/bootstrap-datepicker.css'))
            ->prependStylesheet($this->basePath('assets/css/select2-bootstrap.css'))
            ->prependStylesheet($this->basePath('assets/css/select2.css'))
            ->prependStylesheet($this->basePath('assets/css/all.min.css'))
            ->prependStylesheet($this->basePath('assets/css/bootstrap.min.css'));
        ?>
        <?php if($this->action == 'curso'){ ?>
            <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/bootstrap3-wysihtml5.min.css'); ?>"></link>
        <?php } ?>
        <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500&display=swap" rel="stylesheet"> 
        <?php echo $this->headScript(); ?>
    </head>
    <body class="<?php echo strtolower(explode('\\',$this->controller)[0]); ?>">
        <header class="white fixed-top">
            <div class="container-fluid">
                <?php echo $this->partial('header'); ?>
            </div>
        </header>
        <div class="content" id="main">
            <?php echo $this->content; ?>
        </div>
        <footer class="container">
            <div class="row">
                <div class="col-12">

                </div>
                <input type="hidden" id="baseUrl" value="<?php echo $this->basePath(); ?>" />
            </div>
        </footer>
        <?php echo $this->inlineScript()
                ->prependFile($this->basePath('assets/js/site.js?v=1.1'))
                ->prependFile($this->basePath('assets/js/bootstrap-datepicker.js')) 
                ->prependFile($this->basePath('assets/js/bootstrap-tabcollapse.js'))
                ->prependFile($this->basePath('assets/js/select2.js'))
                ->prependFile($this->basePath('assets/js/all.js'))
                ->prependFile($this->basePath('assets/js/bootstrap.min.js'))
                ->prependFile($this->basePath('assets/js/popper.min.js'))
                ->prependFile($this->basePath('/assets/js/jquery-3.4.1.min.js'));
        ?>
        <?php if($this->action == 'curso'){ ?>
            <!-- <script src='https://cdn.tiny.cloud/1/ggcx6kdi0kkmh9pnh2q7vz2bwbv4ch1n32ww6rhz0236xdxz/tinymce/5/tinymce.min.js' referrerpolicy="origin"></script> -->
            <script src="<?php echo $this->basePath('assets/js/ckeditor/ckeditor.js'); ?>"></script>
            <script src="<?php echo $this->basePath('assets/js/curso.js?V=1.1'); ?>"></script>
        <?php } ?>
        <?php echo $this->partial('footer'); ?>
    </body>
</html>