<?php use Application\Model\Utility\Utilidades; ?>
<div class="container">
    <div class="row">
        <div class="col-12 col-md-8 offset-md-2">
            <h1><i class="fa fa-exclamation-triangle"></i> Error de permisos</h1>
        </div>
        <div class="col-xs-12 col-md-8 offset-md-2">
            <?php Utilidades::muestraMensaje(null,null,'Lo sentimos, no tiene autorización para acceder a la información solicitada.',null,null,false); ?>
        </div>
    </div>
</div>

